import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

const Home = (props) => {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results />
    </div>
  );
};

export default Home;

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;

  const request = await fetch(
    `${process.env.BASE_URL}${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  )
    .then((res) => res.json())
    .catch((err) => console.log(err));

  return {
    props: {
      results: request.results,
    },
  };
};
